PLAT=Ubuntu
OSCN=jammy
USING_UFW=0
pivpnforceipv6route=1
IPv4dev=eth0
install_user=ubuntu
install_home=/home/ubuntu
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=9.9.9.9
pivpnDNS2=149.112.112.112
pivpnHOST=127.0.0.1
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=1
INPUT_CHAIN_EDITEDv6=
FORWARD_CHAIN_EDITEDv6=
pivpnPROTO=udp
pivpnMTU=1420
pivpnDEV=wg0
pivpnNET=10.215.24.0
subnetClass=24
pivpnenableipv6=0
AllowedIPs = 10.0.0.0/16, 10.215.24.0/24
UNATTUPG=1
INSTALLED_PACKAGES=(dnsutils grepcidr net-tools bsdmainutils iptables-persistent qrencode)

